name: Vercel Production Deployment

on: 
  push:
    branches:
      - main
jobs: 
  install: 
    name: Install
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile --production=false
          yarn list | grep tsc-alias  # Verify installation

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with: 
          name: yarn-dependencies
          path: |
            node_modules/
            .yarn/cache/
          retention-days: 1

  build: 
    name: Build
    needs: install
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Download cached dependencies
        uses: actions/download-artifact@v4
        with: 
          name: yarn-dependencies
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      
      - name: Build Project
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: dist
          path: |
            dist/
            package.json
            yarn.lock
            vercel.json
          retention-days: 1

  deploy:
    name: Production Deployment
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: download build Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: dist
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} 
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

